### ISSUE TITLE
playground:6 av mappings :  storepos is not defined

### ISSUE THREAD

**Issue by radorossum** [gibber-cc/gibber#74] opened 2021-11-19 16:48 UTC
bundle.js:78543 ReferenceError: storepos is not defined

to reproduce run example 6.audiovisual mappings from playground

**Comment by charlieroberts** [comment] 2021-11-19 17:29
Hmmm... can't reproduce. Is there a specific part of the tutorial that gives you problems? Also, what browser / os are you using? 

One last question, is this in the version at gibber.cc/alpha/playground? Or is this using a playground you built yourself? Thanks!

**Comment by radorossum** [comment] 2021-11-19 21:47
works fine in the playground at gibber.cc/alpha/playground. the above issue is after i clone the repo and do npm i and npm start. i had to patch first (see issue #73). i then see the issue in both chrome and brave usually after a few successful drawing commands (e.g. the third, fourth alt-enter).
i tried rebuilding but there are a lot of issues with dependencies. i will file a separate report on that. i can take this to the discord if it is easier. thanks

**Comment by charlieroberts** [comment] 2021-12-31 01:10
OK I think this is fixed in 49b1c8fc5c217bacd4e050330a1712c20e40215c (gibber.graphics.lib). Hopefully the build problems are now resolved as well!

**Closed by charlieroberts** 2021-12-31 01:10 UTC
